nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: mixed

yarnPath: .yarn/releases/yarn-4.8.1.cjs

npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'

logFilters:
  - level: discard
    pattern: "*@workspace:* doesn't provide * requested by *"
